### ISSUE TITLE
What is this sorcery?

### ISSUE THREAD

**Issue by wooorm** [sindresorhus/leven#1]

**Comment by derhuerst** [comment]
FYI: According to its benchmark, [js-levenshtein](https://github.com/gustf/js-levenshtein) is faster than `leven`.

**Comment by xavdid** [comment]
@derhuerst I just got curious because I'm shopping around right now. I added `js-levenshtein` to this and ran the benchmarks: 

```
         483,230 op/s » leven
         415,440 op/s » talisman
         338,893 op/s » levenshtein-edit-distance
         286,522 op/s » fast-levenshtein
          69,746 op/s » levenshtein-component
          27,042 op/s » levdist
          44,645 op/s » ld
          36,210 op/s » natural
          19,060 op/s » levenshtein
         449,497 op/s » js-levenshtein


  Suites:  1
  Benches: 10
  Elapsed: 8,203.74 ms
```

Seems like each benchmark favors their own library ¯\\\_(ツ)_/¯

**Comment by Yomguithereal** [comment]
Actually @gustf really has an edge here. He even contributed to this library. His loop unrolling is the reason why. We were discussing adding it to the lib but got carried away.

**Comment by fabiospampinato** [comment]
Using typed arrays may speed things some more. And depending on the length of the longer string the function may even decide to use smaller typed arrays (the edit distance can't be higher than the length of the longer string).
