### ISSUE TITLE
TypeError: right.charCodeAt is not a function

### ISSUE THREAD

**Issue by larsroettig** [sindresorhus/leven#19]
v10.21.0/lib/node_modules/vsce/node_modules/leven/index.js:26
```
	while (leftLength > 0 && (left.charCodeAt(~-leftLength) === right.charCodeAt(~-rightLength))) {
                                                                  ^
TypeError: right.charCodeAt is not a function

   at leven (v10.21.0/lib/node_modules/vsce/node_modules/leven/index.js:26:68)
    at availableCommands.find.c (v10.21.0/lib/node_modules/vsce/out/main.js:146:60)
    at Array.find (<anonymous>)
    at program.help.help (v10.21.0/lib/node_modules/vsce/out/main.js:146:50)
```

**Comment by Yomguithereal** [comment]
Hello @larsroettig. Can you provide the arguments you passed to the function and that led to this error? Is this possible that you did not pass strings to the function somehow?

**Comment by larsroettig** [comment]
Looks like is more a commander or `vsce` bug https://github.com/microsoft/vscode-vsce/blob/f8869d70fc78970c8910025c66ea743d1d5e677a/src/main.ts#L202
