### ISSUE TITLE
ReadMe does not explain well how to import the module on a Node Server

### ISSUE THREAD

**Issue by renzi-fidele-frontend** [sindresorhus/leven#22]
when using the regular snippet to import the module in a js server, it throwns an CommonJs Error
`const leven = require("leven")`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by renzi-fidele-frontend** [comment]
Hello sir Sindresorhus, I have made a pull request with a simple solution, I don't know if you accept or not

**Comment by renzi-fidele-frontend** [comment]
The solution of adding type module to the package.json, forces the developer to replace all the require statement with also import
